[program:seofast-horizon]
process_name=%(program_name)s
command=/opt/cpanel/ea-php84/root/usr/bin/php /home/belalangturbo/juki.eu.org/artisan horizon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=belalangturbo
numprocs=1
redirect_stderr=true
stdout_logfile=/home/belalangturbo/juki.eu.org/storage/logs/horizon.log
stopwaitsecs=3600
