[program:seofast-worker]
process_name=%(program_name)s_%(process_num)02d
command=/opt/cpanel/ea-php84/root/usr/bin/php /home/belalangturbo/juki.eu.org/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=belalangturbo
numprocs=1
redirect_stderr=true
stdout_logfile=/home/belalangturbo/juki.eu.org/storage/logs/worker.log
stopwaitsecs=3600
