<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Content;
use App\Models\SiloBlueprint;
use App\Models\AiGenerationJob;
use App\Jobs\Ai\ProcessAiGenerationJob;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ContentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $contents = Content::withoutGlobalScopes()
            ->where('status', 'published')
            ->with(['siloBlueprint', 'latestUrlInspection'])
            ->latest()
            ->paginate(20);

        return view('admin.content.index', compact('contents'));
    }

    /**
     * Display a listing of the Pra Post (Blueprint) contents ready for AI generation.
     */
    public function prapost()
    {
        // Show blueprint status so user can generate blueprints
        $contents = Content::withoutGlobalScopes()
            ->whereIn('status', ['blueprint', 'failed_cqi'])
            ->with(['siloBlueprint'])
            ->latest()
            ->paginate(20);

        return view('admin.content.prapost', compact('contents'));
    }

    /**
     * Display a listing of Draft contents generated by AI.
     */
    public function drafts()
    {
        $contents = Content::withoutGlobalScopes()
            ->whereIn('status', ['draft', 'needs_reoptimize'])
            ->with(['siloBlueprint'])
            ->latest()
            ->paginate(20);

        return view('admin.content.drafts', compact('contents'));
    }

    /**
     * Show the form for creating a new resource (Write with AI).
     */
    public function create()
    {
        $activeJobs = AiGenerationJob::withoutGlobalScopes()
            ->where(function ($q) {
                $q->whereIn('status', ['pending', 'processing', 'phase_1', 'phase_2', 'phase_3', 'phase_4', 'phase_5', 'phase_6', 'phase_7'])
                  ->orWhere(function ($q2) {
                      $q2->whereIn('status', ['failed', 'failed_cqi', 'completed'])
                         ->where('updated_at', '>=', now()->subHours(12));
                  });
            })
            ->with(['content' => function($q) {
                $q->withoutGlobalScopes();
            }])
            ->latest()
            ->get();
            
        $processingContents = Content::withoutGlobalScopes()
            ->where('status', 'ai_processing')
            ->latest()
            ->get();

        return view('admin.content.create', compact('activeJobs', 'processingContents'));
    }

    /**
     * Store a newly created resource in storage (Dispatch AI Generator).
     */
    public function store(Request $request)
    {
        $request->validate([
            'target_keyword' => 'required|string|max:255',
            'hierarchy_level' => 'required|string|in:pillar,cluster,sub_cluster',
            'silo_blueprint_id' => 'required|exists:silo_blueprints,id',
        ]);

        $slug = Str::slug($request->target_keyword);

        // Check for duplicate slugs
        $exists = Content::withoutGlobalScopes()->where(function($q) use ($slug) {
            $q->where('slug', $slug)->orWhere('slug', 'LIKE', '%"id":"'.$slug.'"%');
        })->exists();
        if ($exists) {
            $slug .= '-' . rand(100, 999);
        }

        $generateAi = $request->has('generate_ai');

        // Create Content model
        $content = Content::create([
            'tenant_id'        => \App\Models\Tenant::first()?->id ?? 1,
            'silo_blueprint_id' => $request->silo_blueprint_id,
            'target_keyword'   => $request->target_keyword,
            'slug'             => ['id' => $slug],
            'meta_title'       => ['id' => ucwords($request->target_keyword) . ' - SEOFAST'],
            'meta_description' => ['id' => 'Panduan taktis terperinci mengenai ' . $request->target_keyword . ' untuk optimasi mesin pencari.'],
            'hierarchy_level' => $request->hierarchy_level,
            'status' => $generateAi ? 'ai_processing' : 'blueprint',
        ]);

        // Calculate crawl priority score: pillar gets highest, cluster medium, sub_cluster lowest
        $hierarchyWeight = match($request->hierarchy_level) {
            'pillar' => 1.0,
            'cluster' => 0.6,
            'sub_cluster' => 0.3,
            default => 0.3,
        };
        $searchVolume = (int) $request->get('search_volume', 0);
        $searchVolumeWeight = min($searchVolume / 1000, 1.0) * 0.4;
        $crawlPriority = round(($searchVolumeWeight) + ($hierarchyWeight * 0.6), 2);
        $content->update(['crawl_priority_score' => $crawlPriority]);

        if ($generateAi) {
            // Create AI Generation Job
            $job = AiGenerationJob::create([
                'tenant_id' => \App\Models\Tenant::first()?->id ?? 1,
                'content_id' => $content->id,
                'job_type' => 'initial_generation',
                'status' => 'pending',
                'llm_model_used' => \App\Models\SystemSetting::get('ai_model', 'gpt-4o'),
            ]);

            // Dispatch background processing job
            ProcessAiGenerationJob::dispatch($content->id, $job->id);

            return redirect()->route('admin.content.index')
                ->with('success', 'AI Generation Job has been queued. The article is being written in 4 distinct quality phases!');
        }

        return redirect()->route('admin.content.index')
            ->with('success', 'Keyword manually added as Blueprint!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Content $content)
    {
        $job = AiGenerationJob::withoutGlobalScopes()->where('content_id', $content->id)->latest()->first();

        return view('admin.content.show', compact('content', 'job'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Content $content)
    {
        $siloBlueprints = SiloBlueprint::withoutGlobalScopes()->get();

        return view('admin.content.edit', compact('content', 'siloBlueprints'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Content $content)
    {

        $request->validate([
            'target_keyword' => 'required|string|max:255',
            'hierarchy_level' => 'required|string|in:pillar,cluster,sub_cluster',
            'silo_blueprint_id' => 'required|exists:silo_blueprints,id',
            'body_raw' => 'nullable|string',
            'rendered_html_path' => 'nullable|string',
            'meta_title' => 'nullable|string|max:70',
            'meta_description' => 'nullable|string|max:160',
            'status' => 'required|string',
            'canonical' => 'nullable|url',
            'robots' => 'nullable|string',
            'og_title' => 'nullable|string',
            'og_description' => 'nullable|string',
            'og_image' => 'nullable|url',
            'schema_type' => 'nullable|string',
            'schema_custom_json' => 'nullable|string',
            'featured_image_upload' => 'nullable|image|mimes:jpeg,png,jpg,webp|max:2048',
            'featured_image_url' => 'nullable|string',
            'published_at' => 'nullable|date',
        ]);

        $updateData = $request->except(['canonical', 'robots', 'og_title', 'og_description', 'og_image', 'schema_type', 'schema_custom_json', 'featured_image_upload']);

        if ($request->hasFile('featured_image_upload')) {
            $path = $request->file('featured_image_upload')->store('content-images', 'public');
            $updateData['featured_image_url'] = '/storage/' . $path;
        }

        $content->update($updateData);

        // Build schema
        $schema = null;
        if ($request->schema_custom_json) {
            $parsed = json_decode($request->schema_custom_json, true);
            if (is_array($parsed)) {
                $schema = $parsed;
            }
        }
        if (!$schema && $request->schema_type && $request->schema_type !== 'None') {
            $schema = ['@type' => $request->schema_type];
        }

        // Update polymorphic SEO meta
        $content->updateSeoMeta([
            'title' => $request->meta_title,
            'description' => $request->meta_description,
            'canonical' => $request->canonical,
            'robots' => $request->robots ?? 'index, follow',
            'og_title' => $request->og_title,
            'og_description' => $request->og_description,
            'og_image' => $request->og_image,
            'schema' => $schema,
        ]);

        return redirect()->route('admin.content.show', $content->id)
            ->with('success', 'Content successfully updated manually.');
    }

    /**
     * Trigger AI Generation for a manual Blueprint.
     */
    public function generateAi(Content $content)
    {
        // Set status to ai_processing
        $content->update(['status' => 'ai_processing']);

        // Check if there's already a pending/processing job
        $existingJob = AiGenerationJob::withoutGlobalScopes()
            ->where('content_id', $content->id)
            ->whereIn('status', ['pending', 'processing'])
            ->first();

        if (!$existingJob) {
            $job = AiGenerationJob::create([
                'tenant_id'  => $content->tenant_id ?? (\App\Models\Tenant::first()?->id ?? 1),
                'content_id' => $content->id,
                'job_type'   => 'initial_generation',
                'status'     => 'pending',
                'retry_count'=> 0
            ]);

            ProcessAiGenerationJob::dispatch($content->id, $job->id);
            
            // Trigger background worker for shared hosting / Windows safely
            $php = PHP_BINARY;
            $artisan = base_path('artisan');
            if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
                if (function_exists('popen') && function_exists('pclose')) {
                    pclose(popen("start /B {$php} {$artisan} queue:work --stop-when-empty > NUL", "r"));
                }
            } else {
                if (function_exists('exec')) {
                    exec("{$php} {$artisan} queue:work --stop-when-empty > /dev/null 2>&1 &");
                }
            }
        }

        return redirect()->route('admin.content.create')->with('success', 'AI Generation started for ' . $content->title);
    }

    /**
     * Register content IDs for AI generation and return the list.
     * The frontend will call generateSingle() for each one sequentially via AJAX.
     */
    public function bulkGenerateAi(Request $request)
    {
        $request->validate([
            'content_ids'   => 'required|array',
            'content_ids.*' => 'exists:contents,id',
            'target_status' => 'nullable|string|in:draft,published',
        ]);

        $targetStatus = $request->input('target_status', 'draft');
        $tenantId     = \App\Models\Tenant::first()?->id ?? 1;
        $queue        = [];

        foreach ($request->content_ids as $id) {
            $content = Content::withoutGlobalScopes()->find($id);
            if (!$content || !in_array($content->status, ['blueprint', 'draft', 'failed_cqi', 'ai_processing'])) {
                continue;
            }

            // Skip if already actively being processed
            $alreadyActive = AiGenerationJob::withoutGlobalScopes()
                ->where('content_id', $content->id)
                ->whereIn('status', ['pending', 'processing', 'phase_1', 'phase_2', 'phase_3', 'phase_4'])
                ->exists();
            if ($alreadyActive) continue;

            // Reuse existing job if it failed, so we can resume
            $job = AiGenerationJob::withoutGlobalScopes()
                ->where('content_id', $content->id)
                ->whereIn('status', ['failed', 'failed_cqi', 'completed'])
                ->first();

            if ($job) {
                $job->update([
                    'status'      => 'pending',
                    'retry_count' => $job->retry_count + 1,
                ]);
            } else {
                $job = AiGenerationJob::create([
                    'tenant_id'   => $content->tenant_id ?? $tenantId,
                    'content_id'  => $content->id,
                    'job_type'    => 'initial_generation',
                    'status'      => 'pending',
                    'retry_count' => 0,
                ]);
            }

            $content->update(['status' => 'ai_processing']);

            $queue[] = [
                'job_id'        => $job->id,
                'content_id'    => $content->id,
                'target_status' => $targetStatus,
                'keyword'       => $content->target_keyword,
                'title'         => $content->title,
            ];
        }

        return response()->json([
            'success' => true,
            'queue'   => $queue,
            'count'   => count($queue),
        ]);
    }

    /**
     * Generate a single content article synchronously.
     * Called by the frontend one content at a time via AJAX.
     * Runs the full Phase 1→4 pipeline in one HTTP request.
     */
    public function generateSingle(Request $request)
    {
        @set_time_limit(300);
        @ini_set('memory_limit', '512M');

        // Gunakan StreamedResponse untuk mencegah Cloudflare 524 Timeout.
        // Cloudflare akan memutus koneksi jika tidak ada data yang dikirim selama 100 detik.
        // Dengan StreamedResponse, kita mengirim HTTP Header dan satu byte spasi terlebih dahulu.
        return response()->stream(function () use ($request) {
            // Kirim spasi untuk memulai response body dan mencegah timeout
            echo " ";
            if (ob_get_level() > 0) ob_flush();
            flush();

            // Eksekusi proses berat
            $result = $this->_doGenerateSingle($request);

            // Kirim JSON aslinya (spasi di awal akan diabaikan oleh JSON.parse di frontend)
            echo json_encode($result);
            if (ob_get_level() > 0) ob_flush();
            flush();
        }, 200, [
            'Content-Type'      => 'application/json',
            'X-Accel-Buffering' => 'no', // Disable Nginx buffering
            'Cache-Control'     => 'no-cache',
            'Connection'        => 'keep-alive',
        ]);
    }

    private function _doGenerateSingle(Request $request)
    {
        set_time_limit(0);
        ignore_user_abort(true);

        try {
            $request->validate([
                'content_id'    => 'required|exists:contents,id',
                'job_id'        => 'required|exists:ai_generation_jobs,id',
                'target_status' => 'nullable|string|in:draft,published',
            ]);

            // RELEASE SESSION LOCK IMMEDIATELY
            // This prevents subsequent AJAX polling requests from hanging and causing Cloudflare 524 timeouts
            // while the background process is running (since PHP default file session blocks concurrent requests).
            if ($request->hasSession()) {
                $request->session()->save();
            }

            $content      = Content::withoutGlobalScopes()->find($request->content_id);
            $job          = AiGenerationJob::withoutGlobalScopes()->find($request->job_id);
            $targetStatus = $request->input('target_status', 'draft');
            $logs         = [];

            if (!$content || !$job) {
                return ['success' => false, 'error' => 'Content or Job not found.', 'logs' => []];
            }

            if ($job->status === 'completed') {
                return [
                    'success' => true,
                    'keyword' => $content->target_keyword,
                    'title'    => $content->title,
                    'cqi'      => $content->cqi_score,
                    'status'   => $content->status,
                    'logs'     => [['level' => 'success', 'message' => '✅ Artikel telah berhasil diselesaikan oleh background process.']]
                ];
            }

            $lockKey = "ai_job_lock_{$job->id}";
            $lock = \Illuminate\Support\Facades\Cache::lock($lockKey, 120);
            if (!$lock->get()) {
                return ['success' => true, 'status' => 'wait', 'keyword' => $content->target_keyword, 'logs' => [['level' => 'running', 'message' => 'Proses masih berjalan di latar belakang (menunggu 10d)...']]];
            }

            try {

            $addLog = function(string $level, string $message) use (&$logs) {
                $logs[] = ['level' => $level, 'message' => $message];
                \Illuminate\Support\Facades\Log::info("AI [{$level}] {$message}");
                echo " ";
                if (ob_get_level() > 0) ob_flush();
                flush();
            };

            if (!$content || !$job) {
                return ['success' => false, 'error' => 'Content or Job not found.', 'logs' => []];
            }

            $keyword     = $content->target_keyword;
            $seedKeyword = $content->siloBlueprint?->seed_keyword ?? $keyword;
            $lang        = $content->siloBlueprint?->target_language ?? 'id';
            $country     = $content->siloBlueprint?->target_country ?? 'ID';
            $tenant      = $content->tenant;

            $job->update(['status' => 'phase_1', 'started_at' => now()]);
            $addLog('info', "Mulai Phase 1: Generating draft untuk [{$keyword}]...");

                        // ── PHASE 1: LSI/Entity Keywords ─────────────────────────────
            $lsi = $job->phase_1_lsi;
            if (!$lsi) {
                $addLog('info', "Mulai Phase 1: Generating entitas & LSI keywords untuk [{$keyword}]...");
                $aiService1 = new \App\Services\AIService($tenant, 'default');
                
                $sysP1 = \App\Models\SystemSetting::get('ai_prompt_phase1_sys',
                    "You are an Expert SEO Strategist. Generate a list of semantic entities and LSI keywords relevant to '{keyword}'. Return the list as a simple comma-separated string.");
                $sysP1 .= "\n\nIMPORTANT: Jangan pakai basa-basi di awal maupun di akhir balasan. Berikan hasil akhirnya saja langsung.";
                $userP1 = "Topic: {$keyword}\nLanguage: {$lang}\nCountry: {$country}";
                
                $lsi = $aiService1->generate($sysP1, $userP1);
                
                if (!$lsi || mb_strlen(trim($lsi)) < 10) {
                    $diags = $aiService1->getLastDiagnostics();
                    $reason = end($diags)['error'] ?? 'Unknown API error or timeout';
                    throw new \Exception("Phase 1 gagal menghasilkan LSI keywords. Reason: " . $reason);
                }
                
                $job->update(['status' => 'phase_2', 'phase_1_lsi' => $lsi]);
                $addLog('success', "Phase 1 SELESAI | LSI: " . mb_strlen($lsi) . " karakter");
                return ['success' => true, 'status' => 'continue', 'logs' => $logs, 'keyword' => $keyword];
            } else {
                $addLog('info', "Memulihkan LSI Phase 1 dari sesi sebelumnya...");
            }

            // ── PHASE 2: Generate Content & Inject Links ─────────────────────────────
            $draft = $job->phase_1_draft;
            if (!$draft) {
                $addLog('info', "Mulai Phase 2: Generating konten awal untuk [{$keyword}]...");
                $aiService2 = new \App\Services\AIService($tenant, 'default');

                $deterministicLinks = \App\Models\DeterministicLink::where('source_content_id', $content->id)
                    ->with('targetContent')->get();
                $linkInstructions = '';
                if ($deterministicLinks->isNotEmpty()) {
                    $linkInstructions = "\n\nMANDATORY INTERNAL LINKS (Embed organically in text using Markdown):\n";
                    foreach ($deterministicLinks as $link) {
                        $url = url('/blog/' . ($link->targetContent?->slug ?? '#'));
                        $linkInstructions .= "- [{$link->anchor_text}]({$url})\n";
                    }
                }

                $sysP2 = \App\Models\SystemSetting::get('ai_prompt_phase2_sys',
                    "You are an Expert SEO Writer writing in {lang}. Write a comprehensive article draft (minimum 800 words) using the provided LSI keywords. **Make the LSI keywords bold**. You must naturally inject the provided MANDATORY INTERNAL LINKS using Markdown. Return ONLY the article draft in Markdown.");
                $sysP2 .= "\n\nIMPORTANT: Jangan pakai basa-basi di awal maupun di akhir konten. Berikan hasil akhirnya saja langsung.";
                $userP2 = "Keyword: **{$keyword}**\nSeed: {$seedKeyword}\nLSI Keywords: {$lsi}\n\nRequirements:\n- Minimum 800 words\n- Use H2 and H3 headings\n{$linkInstructions}\nDo NOT output the LSI list separately, just weave everything seamlessly.";

                $draft = $aiService2->generate($sysP2, $userP2);

                if (!$draft || mb_strlen(trim($draft)) < 300) {
                    $diags = $aiService2->getLastDiagnostics();
                    $reason = end($diags)['error'] ?? 'Unknown API error or timeout';
                    throw new \Exception("Phase 2 gagal menghasilkan draf konten yang valid. Reason: " . $reason);
                }

                $job->update(['status' => 'phase_3', 'phase_1_draft' => $draft]);
                $addLog('success', "Phase 2 SELESAI | Draft: " . mb_strlen($draft) . " karakter");
                return ['success' => true, 'status' => 'continue', 'logs' => $logs, 'keyword' => $keyword];
            } else {
                $addLog('info', "Memulihkan Draft Phase 2 dari sesi sebelumnya...");
            }

            // ── PHASE 3: Critical Questions ──────────────────────────
            $critique = $job->phase_2_critique;
            if (!$critique || !is_array($critique)) {
                $addLog('info', "Phase 3: Generating Pertanyaan Kritis untuk [{$keyword}]...");
                $aiService3 = new \App\Services\AIService($tenant, 'default');
                $sysP3 = \App\Models\SystemSetting::get('ai_prompt_phase3_sys',
                    "You are a strict Senior SEO Content Auditor. Read the draft and generate a list of 'Critical Questions' that a human expert would ask, which this draft currently fails to answer adequately. Respond ONLY with a valid JSON array of strings:\n[\"Question 1?\", \"Question 2?\"]");
                $sysP3 .= "\n\nIMPORTANT: Jangan pakai basa-basi di awal maupun di akhir balasan. Berikan hasil akhirnya saja langsung dalam format JSON.";
                $critique = $aiService3->generateJson($sysP3, "Keyword: {$keyword}\n\nDraft:\n{$draft}");

                if (!$critique || !is_array($critique) || (isset($critique['cqi_score']))) {
                    $critique = ['Apa saja strategi lanjutan yang belum dibahas?', 'Bagaimana cara menghindari kesalahan umum?'];
                    $addLog('warn', "Phase 3: JSON array gagal di-parse, menggunakan default pertanyaan.");
                }

                $job->update(['status' => 'phase_4', 'phase_2_critique' => $critique]);
                $addLog('info', "Phase 3 SELESAI | Dihasilkan " . count($critique) . " Pertanyaan Kritis");
                return ['success' => true, 'status' => 'continue', 'logs' => $logs, 'keyword' => $keyword];
            } else {
                $addLog('info', "Memulihkan Pertanyaan Kritis Phase 3 dari sesi sebelumnya...");
            }

            // ── PHASE 4: Answer Questions ──────────────────────────────────
            $answers = $job->phase_4_answers;
            if (!$answers) {
                $addLog('info', "Phase 4: Menjawab pertanyaan kritis...");
                $aiService4 = new \App\Services\AIService($tenant, 'default');
                $criticalQs = implode("\n- ", is_array($critique) ? $critique : ['Berikan pembahasan lebih mendalam.']);
                
                $sysP4 = \App\Models\SystemSetting::get('ai_prompt_phase4_sys',
                    "You are a Subject Matter Expert in {lang}. Provide highly detailed, deeply researched answers to the following 'Critical Questions'. Return ONLY the answers in Markdown formatting.");
                $sysP4 = strtr($sysP4, ['{lang}' => $lang]);
                $sysP4 .= "\n\nIMPORTANT: Jangan pakai basa-basi di awal maupun di akhir balasan. Berikan hasil akhirnya saja langsung.";
                $userP4 = "Topic: **{$keyword}**\n\nQuestions to Answer:\n- {$criticalQs}";

                $answers = $aiService4->generate($sysP4, $userP4);

                if (!$answers || mb_strlen(trim($answers)) < 100 || str_contains($answers, '{"error"')) {
                    $diags = $aiService4->getLastDiagnostics();
                    $reason = end($diags)['error'] ?? 'Unknown API error or timeout';
                    throw new \Exception("Phase 4 gagal menghasilkan jawaban yang valid. Reason: " . $reason);
                }

                $job->update(['status' => 'phase_5', 'phase_4_answers' => $answers]);
                $addLog('success', "Phase 4 SELESAI | Answers: " . mb_strlen($answers) . " karakter");
                return ['success' => true, 'status' => 'continue', 'logs' => $logs, 'keyword' => $keyword];
            } else {
                $addLog('info', "Memulihkan Answers Phase 4 dari sesi sebelumnya...");
            }
            
            // ── PHASE 5: Combine into Extended Content ──────────────────────────────────
            $combined = $job->phase_5_combined;
            if (!$combined) {
                $addLog('info', "Phase 5: Menggabungkan menjadi Extended Content...");
                $aiService5 = new \App\Services\AIService($tenant, 'default');
                
                $sysP5 = \App\Models\SystemSetting::get('ai_prompt_phase5_sys',
                    "You are a Master SEO Content Editor writing in {lang}. Rewrite and drastically expand the original draft by seamlessly weaving in the provided 'Detailed Answers'. Preserve all existing Markdown links EXACTLY as they are. Do NOT add an FAQ section; weave the answers seamlessly into the body paragraphs with proper H2/H3 headings. Return ONLY the improved Markdown.");
                $sysP5 = strtr($sysP5, ['{lang}' => $lang]);
                $sysP5 .= "\n\nIMPORTANT: Jangan pakai basa-basi di awal maupun di akhir konten. Berikan hasil akhirnya saja langsung.";
                $userP5 = "Keyword: **{$keyword}**\n\nOriginal Draft:\n{$draft}\n\nDetailed Answers to weave in:\n{$answers}";

                $combined = $aiService5->generate($sysP5, $userP5);

                if (!$combined || mb_strlen(trim($combined)) < 300 || str_contains($combined, '{"error"')) {
                    $diags = $aiService5->getLastDiagnostics();
                    $reason = end($diags)['error'] ?? 'Unknown API error or timeout';
                    throw new \Exception("Phase 5 gagal menghasilkan konten kombinasi yang valid. Reason: " . $reason);
                }

                $job->update(['status' => 'phase_6', 'phase_5_combined' => $combined]);
                $addLog('success', "Phase 5 SELESAI | Combined: " . mb_strlen($combined) . " karakter");
                return ['success' => true, 'status' => 'continue', 'logs' => $logs, 'keyword' => $keyword];
            } else {
                $addLog('info', "Memulihkan Extended Content Phase 5 dari sesi sebelumnya...");
            }

            // ── PHASE 6: HTML Conversion ───────────────────────────
            $finalBody = $job->phase_6_html;
            if (!$finalBody) {
                $addLog('info', "Phase 6: Konversi ke HTML & optimasi akhir...");
                $aiService6 = new \App\Services\AIService($tenant, 'default');

                $sysP6 = \App\Models\SystemSetting::get('ai_prompt_phase6_sys',
                    "You are a Chief Content Editor writing in {lang}. Do a final polish of the article. Preserve all existing Markdown links exactly as they are. Output the final result as clean HTML (using <h2>, <h3>, <p>, <strong>, <a>, etc.), NOT Markdown. Do not include ```html or <html> tags, just the inner HTML body. Keep the comprehensive length.");
                $sysP6 = strtr($sysP6, ['{lang}' => $lang]);
                
                // CRITICAL: Force the AI to wrap output to prevent conversational filler from leaking
                $sysP6 .= "\n\nCRITICAL REQUIREMENT: You MUST wrap your ENTIRE final HTML output exactly inside <article_body> and </article_body> tags. Do not include any explanations outside these tags.";
                $sysP6 .= "\n\nIMPORTANT: Jangan pakai basa-basi di awal maupun di akhir artikel yang dibuat. Berikan hasil akhirnya saja langsung.";
                
                $userP6 = "Keyword: **{$keyword}**\n\nArticle:\n{$combined}";

                $finalBody = $aiService6->generate($sysP6, $userP6);
                if ($finalBody) {
                    $finalBody = preg_replace('/^```html|```$/mi', '', trim($finalBody)); // Remove markdown HTML blocks if any
                    
                    // Extract strictly from <article_body> if present
                    if (preg_match('/<article_body>([\s\S]*?)<\/article_body>/i', $finalBody, $matches)) {
                        $finalBody = trim($matches[1]);
                    } else {
                        // Fallback extraction if AI ignored the wrap instruction
                        if (preg_match('/<(?:h[1-3]|p|div|section)[\s\S]*>/i', $finalBody, $matches)) {
                            $finalBody = $matches[0];
                        }
                    }
                }

                if (!$finalBody || mb_strlen(trim($finalBody)) < 300 || str_contains($finalBody, '{"error"')) {
                    $diags = $aiService6->getLastDiagnostics();
                    $reason = end($diags)['error'] ?? 'Unknown API error or timeout';
                    throw new \Exception("Phase 6 gagal mengkonversi ke HTML dengan valid. Reason: " . $reason);
                }

                $job->update(['status' => 'phase_7', 'phase_6_html' => $finalBody]);
                $addLog('success', "Phase 6 SELESAI | HTML: " . mb_strlen($finalBody) . " karakter");
                return ['success' => true, 'status' => 'continue', 'logs' => $logs, 'keyword' => $keyword];
            } else {
                $addLog('info', "Memulihkan HTML Phase 6 dari sesi sebelumnya...");
            }

            // ── Save to DB & Phase 7 (SEO Meta) ───────────────────────────────
            $blogPrefix  = \App\Models\SystemSetting::get('permalink_blog', 'blog');
            $contentHash = hash('sha256', $finalBody);
            
            $cqiScore = null;

            $job->update([
                'status'        => 'completed',
                'completed_at'  => now(),
            ]);

            $deterministicLinks = \App\Models\DeterministicLink::where('source_content_id', $content->id)->get();
            if ($deterministicLinks->isNotEmpty()) {
                \App\Models\DeterministicLink::where('source_content_id', $content->id)
                    ->update([
                        'is_injected_successfully' => true,
                        'injected_at' => now()
                    ]);
            }

            $content->body_raw = $finalBody;
            $content->update([
                'content_hash' => $contentHash,
                'status'       => $targetStatus,
                'published_at' => $content->published_at ?? now(),
            ]);
            $content->save();

            // ── Phase 7: SEO Meta (non-blocking) ─────────────────────────────
            try {
                $aiService7 = new \App\Services\AIService($tenant, 'default');
                $addLog('info', "Phase 7: Generating SEO Meta...");
                $metaTitlePrompt = str_replace('{keyword}', $keyword, \App\Models\SystemSetting::get('ai_prompt_meta_title',
                    'Write a highly click-worthy SEO title for "{keyword}". Max 60 chars. Return ONLY the title.'));
                $metaTitlePrompt .= "\n\nIMPORTANT: Jangan pakai basa-basi di awal maupun di akhir balasan. Berikan hasil akhirnya saja langsung.";
                $metaDescPrompt  = str_replace('{keyword}', $keyword, \App\Models\SystemSetting::get('ai_prompt_meta_description',
                    'Write an engaging SEO meta description for "{keyword}". 150-160 chars with CTA. Return ONLY the description.'));
                $metaDescPrompt .= "\n\nIMPORTANT: Jangan pakai basa-basi di awal maupun di akhir balasan. Berikan hasil akhirnya saja langsung.";

                $metaTitle = trim($aiService7->generate('You are an expert SEO specialist.', $metaTitlePrompt), " \t\n\r\"'");
                $metaDesc  = trim($aiService7->generate('You are an expert SEO specialist.', $metaDescPrompt), " \t\n\r\"'");

                $content->updateSeoMeta([
                    'title'          => $metaTitle ?: $content->title,
                    'description'    => $metaDesc,
                    'canonical'      => url('/' . $blogPrefix . '/' . $content->slug),
                    'robots'         => 'index, follow',
                    'og_title'       => $metaTitle ?: $content->title,
                    'og_description' => $metaDesc,
                    'og_image'       => $content->featured_image_url ?: \App\Models\SystemSetting::get('seo_og_image'),
                ]);
                $addLog('success', "Phase 7 SELESAI | SEO Meta dibuat: \"{$metaTitle}\"");
            } catch (\Exception $e) {
                $addLog('warn', "Phase 7 SEO Meta gagal (non-fatal): " . $e->getMessage());
            }

            $addLog('success', "✅ [{$keyword}] GENERATION SELESAI → status: {$targetStatus} | {$contentHash}");


            return [
                'success' => true,
                'keyword' => $keyword,
                'title'    => $content->title,
                'cqi'      => $cqiScore,
                'status'   => $targetStatus,
                'logs'     => $logs,
            ];

            } finally {
                if (isset($lock)) {
                    $lock->release();
                }
            }

        } catch (\Throwable $e) {
            if (isset($lock)) {
                $lock->release();
            }
            if (isset($job) && $job) {
                $job->update(['status' => 'failed', 'error_log' => ['reason' => $e->getMessage()]]);
            }
            if (isset($content) && $content) {
                $content->update(['status' => 'failed_cqi']);
            }
            
            $errorMsg = "FATAL ERROR: " . $e->getMessage() . " on line " . $e->getLine();
            if (isset($addLog)) {
                $addLog('error', $errorMsg);
                return ['success' => false, 'keyword' => $keyword ?? 'Unknown', 'error' => $errorMsg, 'logs' => $logs];
            }
            
            return ['success' => false, 'error' => $errorMsg, 'logs' => []];
        }
    }




    /**
     * Check connectivity to the configured AI provider.
     * Called by the frontend before starting the AI Worker to verify the API
     * key/endpoint is reachable. Returns provider info and ok/error status.
     */
    public function checkConnection()
    {
        $tenant    = \App\Models\Tenant::first();
        $aiService = new \App\Services\AIService($tenant, 'default');
        $result    = $aiService->testConnection();

        return response()->json([
            'ok'          => $result['ok'],
            'provider'    => $result['provider'],
            'model'       => $result['model'],
            'error'       => $result['error'],
            'diagnostics' => $result['diagnostics'] ?? [],
        ]);
    }

    /**
     * Trigger queue worker manually via AJAX.
     * Returns rich per-job status details so the terminal can display
     * phase-by-phase progress information.
     */
    public function workQueue(Request $request)
    {
        if (function_exists('set_time_limit')) {
            @set_time_limit(120);
        }

        $activeStatuses = ['pending', 'processing', 'phase_1', 'phase_2', 'phase_3', 'phase_4', 'phase_5', 'phase_6', 'phase_7'];

        try {
            $hasJobsInQueue = \Illuminate\Support\Facades\DB::table('jobs')->exists();
            $hasMore        = false;
            $logs           = [];

            // --- Take snapshot of all active jobs BEFORE running the worker ---
            $jobsBefore = \App\Models\AiGenerationJob::withoutGlobalScopes()
                ->whereIn('status', $activeStatuses)
                ->with(['content' => fn($q) => $q->withoutGlobalScopes()])
                ->get()
                ->keyBy('id');

            if (!$hasJobsInQueue) {
                // Queue table empty — check for orphaned DB jobs
                $stuckJobs = \App\Models\AiGenerationJob::withoutGlobalScopes()
                    ->whereIn('status', $activeStatuses)
                    ->with(['content' => fn($q) => $q->withoutGlobalScopes()])
                    ->get();

                if ($stuckJobs->isNotEmpty()) {
                    foreach ($stuckJobs as $stuck) {
                        $stuck->update([
                            'status'    => 'failed',
                            'error_log' => ['error' => 'Job execution timed out or was killed by server.'],
                        ]);
                        $stuck->content?->update(['status' => 'failed_cqi']);

                        $logs[] = [
                            'level'   => 'error',
                            'message' => "JOB #{$stuck->id} [{$stuck->content?->target_keyword}] → Cleaned up as STUCK (queue empty but DB shows active)",
                        ];
                    }
                } else {
                    $logs[] = ['level' => 'info', 'message' => 'Queue empty. All jobs finished or no jobs queued.'];
                }

                $hasMore = false;
            } else {
                // Run exactly one queued job
                \Illuminate\Support\Facades\Artisan::call('queue:work', [
                    '--once'           => true,
                    '--force'          => true,
                    '--stop-when-empty'=> true,
                ]);

                // --- Take snapshot AFTER running ---
                $jobsAfter = \App\Models\AiGenerationJob::withoutGlobalScopes()
                    ->with(['content' => fn($q) => $q->withoutGlobalScopes()])
                    ->whereIn('id', $jobsBefore->keys()->toArray())
                    ->get()
                    ->keyBy('id');

                // Also check for any newly dispatched jobs from CQI retries
                $allActiveNow = \App\Models\AiGenerationJob::withoutGlobalScopes()
                    ->whereIn('status', $activeStatuses)
                    ->with(['content' => fn($q) => $q->withoutGlobalScopes()])
                    ->get();

                // Build per-job log lines
                foreach ($jobsBefore as $id => $before) {
                    $after    = $jobsAfter->get($id);
                    $keyword  = $before->content?->target_keyword ?? 'Unknown';
                    $title    = $before->content?->title ?? "Content #{$before->content_id}";
                    $elapsed  = $before->started_at ? now()->diffInSeconds($before->started_at) . 's' : '-';

                    if (!$after) {
                        $logs[] = ['level' => 'info', 'message' => "JOB #{$id} [{$keyword}] → No longer in active list (may have completed or failed)"];
                        continue;
                    }

                    $fromStatus = strtoupper($before->status);
                    $toStatus   = strtoupper($after->status);

                    $phaseLabel = match($after->status) {
                        'phase_1'  => '📝 Phase 1 — Generating Initial Draft',
                        'phase_2'  => '🔍 Phase 2 — Quality Critique & CQI Scoring',
                        'phase_3'  => '✍️  Phase 3 — Expanding & Enriching Content',
                        'phase_4'  => '🎨 Phase 4 — Master Edit & Link Injection',
                        'completed'=> '✅ COMPLETED — Content saved to DB',
                        'failed'   => '❌ FAILED — ' . (($after->error_log['reason'] ?? $after->error_log['error'] ?? 'Unknown error')),
                        'failed_cqi' => '⚠️  CQI FAILED — Retrying Phase 1',
                        default    => strtoupper($after->status),
                    };

                    $cqiInfo    = '';
                    $retryInfo  = '';
                    if ($after->phase_2_critique && isset($after->phase_2_critique['cqi_score'])) {
                        $cqiInfo = " | CQI: {$after->phase_2_critique['cqi_score']}/100";
                    }
                    if ($after->retry_count > 0) {
                        $retryInfo = " | Retry: {$after->retry_count}/2";
                    }

                    $level = match(true) {
                        $after->status === 'failed'     => 'error',
                        $after->status === 'failed_cqi' => 'warn',
                        $after->status === 'completed'  => 'success',
                        default                          => 'info',
                    };

                    // Status transition log
                    if ($fromStatus !== $toStatus) {
                        $logs[] = [
                            'level'   => $level,
                            'message' => "JOB #{$id} [{$keyword}]{$cqiInfo}{$retryInfo} → {$fromStatus} ➜ {$phaseLabel}",
                        ];
                    } else {
                        // Status unchanged (still same phase — running)
                        $logs[] = [
                            'level'   => 'running',
                            'message' => "JOB #{$id} [{$keyword}] — {$phaseLabel}{$cqiInfo}{$retryInfo} (elapsed: {$elapsed})",
                        ];
                    }

                    // If completed, show what content was saved
                    if ($after->status === 'completed') {
                        $bodyLen  = $after->phase_4_final ? mb_strlen($after->phase_4_final) : 0;
                        $cqiFinal = $after->phase_2_critique['cqi_score'] ?? 'N/A';
                        $logs[] = [
                            'level'   => 'success',
                            'message' => "   └─ \"{$title}\" saved | CQI: {$cqiFinal}/100 | Body: {$bodyLen} chars | Status: {$after->content?->status}",
                        ];
                    }

                    // If failed, show the reason
                    if ($after->status === 'failed') {
                        $reason = $after->error_log['reason'] ?? $after->error_log['error'] ?? 'No reason recorded';
                        $logs[] = [
                            'level'   => 'error',
                            'message' => "   └─ REASON: {$reason}",
                        ];
                    }
                }

                // Show count of remaining jobs
                $remainingCount = $allActiveNow->count();
                $hasMore        = $remainingCount > 0;

                if ($hasMore) {
                    $logs[] = [
                        'level'   => 'info',
                        'message' => "─── {$remainingCount} job(s) still in queue. Processing next... ───",
                    ];
                } else {
                    $logs[] = [
                        'level'   => 'success',
                        'message' => '═══ All AI generation jobs completed! ═══',
                    ];
                }
            }

            return response()->json([
                'success' => true,
                'logs'    => $logs,
                'has_more'=> $hasMore,
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'success'  => false,
                'logs'     => [['level' => 'error', 'message' => 'FATAL: ' . $e->getMessage()]],
                'has_more' => \App\Models\AiGenerationJob::withoutGlobalScopes()
                    ->whereIn('status', $activeStatuses)->exists(),
            ]);
        }
    }




    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Content $content)
    {

        $content->delete();

        return redirect()->route('admin.content.index')
            ->with('success', 'Post successfully deleted.');
    }
}
