<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Content;
use App\Models\SiloBlueprint;
use App\Models\AiGenerationJob;
use App\Jobs\Ai\ProcessAiGenerationJob;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ContentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $contents = Content::withoutGlobalScopes()
            ->where('status', 'published')
            ->with(['siloBlueprint', 'latestUrlInspection'])
            ->latest()
            ->paginate(20);

        return view('admin.content.index', compact('contents'));
    }

    /**
     * Display a listing of the Pra Post (Blueprint) contents ready for AI generation.
     */
    public function prapost()
    {
        // Show blueprint status so user can generate blueprints
        $contents = Content::withoutGlobalScopes()
            ->whereIn('status', ['blueprint', 'failed_cqi'])
            ->with(['siloBlueprint'])
            ->latest()
            ->paginate(20);

        return view('admin.content.prapost', compact('contents'));
    }

    /**
     * Display a listing of Draft contents generated by AI.
     */
    public function drafts()
    {
        $contents = Content::withoutGlobalScopes()
            ->whereIn('status', ['draft', 'needs_reoptimize'])
            ->with(['siloBlueprint'])
            ->latest()
            ->paginate(20);

        return view('admin.content.drafts', compact('contents'));
    }

    /**
     * Show the form for creating a new resource (Write with AI).
     */
    public function create()
    {
        $activeJobs = AiGenerationJob::withoutGlobalScopes()
            ->whereIn('status', ['pending', 'processing', 'phase_1', 'phase_2', 'phase_3', 'phase_4'])
            ->with(['content' => function($q) {
                $q->withoutGlobalScopes();
            }])
            ->latest()
            ->get();
            
        $processingContents = Content::withoutGlobalScopes()
            ->where('status', 'ai_processing')
            ->latest()
            ->get();

        return view('admin.content.create', compact('activeJobs', 'processingContents'));
    }

    /**
     * Store a newly created resource in storage (Dispatch AI Generator).
     */
    public function store(Request $request)
    {
        $request->validate([
            'target_keyword' => 'required|string|max:255',
            'hierarchy_level' => 'required|string|in:pillar,cluster,sub_cluster',
            'silo_blueprint_id' => 'required|exists:silo_blueprints,id',
        ]);

        $slug = Str::slug($request->target_keyword);

        // Check for duplicate slugs
        $exists = Content::withoutGlobalScopes()->where(function($q) use ($slug) {
            $q->where('slug', $slug)->orWhere('slug', 'LIKE', '%"id":"'.$slug.'"%');
        })->exists();
        if ($exists) {
            $slug .= '-' . rand(100, 999);
        }

        $generateAi = $request->has('generate_ai');

        // Create Content model
        $content = Content::create([
            'tenant_id'        => \App\Models\Tenant::first()?->id ?? 1,
            'silo_blueprint_id' => $request->silo_blueprint_id,
            'target_keyword'   => $request->target_keyword,
            'slug'             => ['id' => $slug],
            'meta_title'       => ['id' => ucwords($request->target_keyword) . ' - SEOFAST'],
            'meta_description' => ['id' => 'Panduan taktis terperinci mengenai ' . $request->target_keyword . ' untuk optimasi mesin pencari.'],
            'hierarchy_level' => $request->hierarchy_level,
            'status' => $generateAi ? 'ai_processing' : 'blueprint',
        ]);

        // Calculate crawl priority score: pillar gets highest, cluster medium, sub_cluster lowest
        $hierarchyWeight = match($request->hierarchy_level) {
            'pillar' => 1.0,
            'cluster' => 0.6,
            'sub_cluster' => 0.3,
            default => 0.3,
        };
        $searchVolume = (int) $request->get('search_volume', 0);
        $searchVolumeWeight = min($searchVolume / 1000, 1.0) * 0.4;
        $crawlPriority = round(($searchVolumeWeight) + ($hierarchyWeight * 0.6), 2);
        $content->update(['crawl_priority_score' => $crawlPriority]);

        if ($generateAi) {
            // Create AI Generation Job
            $job = AiGenerationJob::create([
                'tenant_id' => \App\Models\Tenant::first()?->id ?? 1,
                'content_id' => $content->id,
                'job_type' => 'initial_generation',
                'status' => 'pending',
                'llm_model_used' => \App\Models\SystemSetting::get('ai_model', 'gpt-4o'),
            ]);

            // Dispatch background processing job
            ProcessAiGenerationJob::dispatch($content->id, $job->id);

            return redirect()->route('admin.content.index')
                ->with('success', 'AI Generation Job has been queued. The article is being written in 4 distinct quality phases!');
        }

        return redirect()->route('admin.content.index')
            ->with('success', 'Keyword manually added as Blueprint!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Content $content)
    {
        $job = AiGenerationJob::withoutGlobalScopes()->where('content_id', $content->id)->latest()->first();

        return view('admin.content.show', compact('content', 'job'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Content $content)
    {
        $siloBlueprints = SiloBlueprint::withoutGlobalScopes()->get();

        return view('admin.content.edit', compact('content', 'siloBlueprints'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Content $content)
    {

        $request->validate([
            'target_keyword' => 'required|string|max:255',
            'hierarchy_level' => 'required|string|in:pillar,cluster,sub_cluster',
            'silo_blueprint_id' => 'required|exists:silo_blueprints,id',
            'body_raw' => 'nullable|string',
            'rendered_html_path' => 'nullable|string',
            'meta_title' => 'nullable|string|max:70',
            'meta_description' => 'nullable|string|max:160',
            'status' => 'required|string',
            'canonical' => 'nullable|url',
            'robots' => 'nullable|string',
            'og_title' => 'nullable|string',
            'og_description' => 'nullable|string',
            'og_image' => 'nullable|url',
            'schema_type' => 'nullable|string',
            'schema_custom_json' => 'nullable|string',
            'featured_image_upload' => 'nullable|image|mimes:jpeg,png,jpg,webp|max:2048',
            'featured_image_url' => 'nullable|string',
            'published_at' => 'nullable|date',
        ]);

        $updateData = $request->except(['canonical', 'robots', 'og_title', 'og_description', 'og_image', 'schema_type', 'schema_custom_json', 'featured_image_upload']);

        if ($request->hasFile('featured_image_upload')) {
            $path = $request->file('featured_image_upload')->store('content-images', 'public');
            $updateData['featured_image_url'] = '/storage/' . $path;
        }

        $content->update($updateData);

        // Build schema
        $schema = null;
        if ($request->schema_custom_json) {
            $parsed = json_decode($request->schema_custom_json, true);
            if (is_array($parsed)) {
                $schema = $parsed;
            }
        }
        if (!$schema && $request->schema_type && $request->schema_type !== 'None') {
            $schema = ['@type' => $request->schema_type];
        }

        // Update polymorphic SEO meta
        $content->updateSeoMeta([
            'title' => $request->meta_title,
            'description' => $request->meta_description,
            'canonical' => $request->canonical,
            'robots' => $request->robots ?? 'index, follow',
            'og_title' => $request->og_title,
            'og_description' => $request->og_description,
            'og_image' => $request->og_image,
            'schema' => $schema,
        ]);

        return redirect()->route('admin.content.show', $content->id)
            ->with('success', 'Content successfully updated manually.');
    }

    /**
     * Trigger AI Generation for a manual Blueprint.
     */
    public function generateAi(Content $content)
    {
        // Set status to ai_processing
        $content->update(['status' => 'ai_processing']);

        // Check if there's already a pending/processing job
        $existingJob = AiGenerationJob::withoutGlobalScopes()
            ->where('content_id', $content->id)
            ->whereIn('status', ['pending', 'processing'])
            ->first();

        if (!$existingJob) {
            $job = AiGenerationJob::create([
                'tenant_id'  => $content->tenant_id ?? (\App\Models\Tenant::first()?->id ?? 1),
                'content_id' => $content->id,
                'job_type'   => 'initial_generation',
                'status'     => 'pending',
                'retry_count'=> 0
            ]);

            ProcessAiGenerationJob::dispatch($content->id, $job->id);
            
            // Trigger background worker for shared hosting / Windows safely
            $php = PHP_BINARY;
            $artisan = base_path('artisan');
            if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
                if (function_exists('popen') && function_exists('pclose')) {
                    pclose(popen("start /B {$php} {$artisan} queue:work --stop-when-empty > NUL", "r"));
                }
            } else {
                if (function_exists('exec')) {
                    exec("{$php} {$artisan} queue:work --stop-when-empty > /dev/null 2>&1 &");
                }
            }
        }

        return redirect()->route('admin.content.create')->with('success', 'AI Generation started for ' . $content->title);
    }

    /**
     * Register content IDs for AI generation and return the list.
     * The frontend will call generateSingle() for each one sequentially via AJAX.
     */
    public function bulkGenerateAi(Request $request)
    {
        $request->validate([
            'content_ids'   => 'required|array',
            'content_ids.*' => 'exists:contents,id',
            'target_status' => 'nullable|string|in:draft,published',
        ]);

        $targetStatus = $request->input('target_status', 'draft');
        $tenantId     = \App\Models\Tenant::first()?->id ?? 1;
        $queue        = [];

        foreach ($request->content_ids as $id) {
            $content = Content::withoutGlobalScopes()->find($id);
            if (!$content || !in_array($content->status, ['blueprint', 'draft', 'failed_cqi', 'ai_processing'])) {
                continue;
            }

            // Skip if already actively being processed
            $alreadyActive = AiGenerationJob::withoutGlobalScopes()
                ->where('content_id', $content->id)
                ->whereIn('status', ['pending', 'processing', 'phase_1', 'phase_2', 'phase_3', 'phase_4'])
                ->exists();
            if ($alreadyActive) continue;

            // Clean up any previous failed jobs for this content
            AiGenerationJob::withoutGlobalScopes()
                ->where('content_id', $content->id)
                ->whereIn('status', ['failed', 'failed_cqi', 'completed'])
                ->delete();

            $job = AiGenerationJob::create([
                'tenant_id'   => $content->tenant_id ?? $tenantId,
                'content_id'  => $content->id,
                'job_type'    => 'initial_generation',
                'status'      => 'pending',
                'retry_count' => 0,
            ]);

            $content->update(['status' => 'ai_processing']);

            $queue[] = [
                'job_id'        => $job->id,
                'content_id'    => $content->id,
                'target_status' => $targetStatus,
                'keyword'       => $content->target_keyword,
                'title'         => $content->title,
            ];
        }

        return response()->json([
            'success' => true,
            'queue'   => $queue,
            'count'   => count($queue),
        ]);
    }

    /**
     * Generate a single content article synchronously.
     * Called by the frontend one content at a time via AJAX.
     * Runs the full Phase 1→4 pipeline in one HTTP request.
     */
    public function generateSingle(Request $request)
    {
        @set_time_limit(300);
        @ini_set('memory_limit', '512M');

        // Gunakan StreamedResponse untuk mencegah Cloudflare 524 Timeout.
        // Cloudflare akan memutus koneksi jika tidak ada data yang dikirim selama 100 detik.
        // Dengan StreamedResponse, kita mengirim HTTP Header dan satu byte spasi terlebih dahulu.
        return response()->stream(function () use ($request) {
            // Kirim spasi untuk memulai response body dan mencegah timeout
            echo " ";
            if (ob_get_level() > 0) ob_flush();
            flush();

            // Eksekusi proses berat
            $result = $this->_doGenerateSingle($request);

            // Kirim JSON aslinya (spasi di awal akan diabaikan oleh JSON.parse di frontend)
            echo json_encode($result);
            if (ob_get_level() > 0) ob_flush();
            flush();
        }, 200, [
            'Content-Type'      => 'application/json',
            'X-Accel-Buffering' => 'no', // Disable Nginx buffering
            'Cache-Control'     => 'no-cache',
            'Connection'        => 'keep-alive',
        ]);
    }

    private function _doGenerateSingle(Request $request)
    {
        try {
            $request->validate([
                'content_id'    => 'required|exists:contents,id',
                'job_id'        => 'required|exists:ai_generation_jobs,id',
                'target_status' => 'nullable|string|in:draft,published',
            ]);

            $content      = Content::withoutGlobalScopes()->find($request->content_id);
            $job          = AiGenerationJob::withoutGlobalScopes()->find($request->job_id);
            $targetStatus = $request->input('target_status', 'draft');
            $logs         = [];

            $addLog = function(string $level, string $message) use (&$logs) {
                $logs[] = ['level' => $level, 'message' => $message];
                \Illuminate\Support\Facades\Log::info("AI [{$level}] {$message}");
                // Send keep-alive byte immediately if in stream mode
                echo " ";
                if (ob_get_level() > 0) ob_flush();
                flush();
            };

            if (!$content || !$job) {
                return ['success' => false, 'error' => 'Content or Job not found.', 'logs' => []];
            }

            $keyword     = $content->target_keyword;
            $seedKeyword = $content->siloBlueprint?->seed_keyword ?? $keyword;
            $lang        = $content->siloBlueprint?->target_language ?? 'id';
            $country     = $content->siloBlueprint?->target_country ?? 'ID';
            $tenant      = $content->tenant;

            $job->update(['status' => 'phase_1', 'started_at' => now()]);
            $addLog('info', "Mulai Phase 1: Generating draft untuk [{$keyword}]...");

            // ── PHASE 1: Draft Generation ─────────────────────────────────────
            $aiService1  = new \App\Services\AIService($tenant, 'default');
            $sysP1  = \App\Models\SystemSetting::get('ai_prompt_phase1_sys',
                "You are an expert SEO Content Writer fluent in {lang}. Write a comprehensive, well-structured article about '{keyword}' targeting readers in {country}. Use proper Markdown formatting with H2 and H3 headings. Apply E-E-A-T principles: include expert insights, real examples, and actionable advice. The article must be at least 1,200 words.");
            $userP1 = \App\Models\SystemSetting::get('ai_prompt_phase1_user',
                "Write a comprehensive, SEO-optimised article in {lang} about: **{keyword}**.\n\nRequirements:\n- Minimum 1,200 words\n- Use H2 and H3 headings\n- Cover: definition, importance, step-by-step guide, common mistakes, conclusion with CTA\n- Incorporate seed keyword '{seed_keyword}' naturally\n- Do NOT use generic filler - every sentence must provide real value");

            $sysP1  = strtr($sysP1,  ['{keyword}' => $keyword, '{seed_keyword}' => $seedKeyword, '{lang}' => $lang, '{country}' => $country]);
            $userP1 = strtr($userP1, ['{keyword}' => $keyword, '{seed_keyword}' => $seedKeyword, '{lang}' => $lang, '{country}' => $country]);

            $draft = $aiService1->generate($sysP1, $userP1);

            // ── Push diagnostics to terminal log ──────────────────────────────
            foreach ($aiService1->getLastDiagnostics() as $diag) {
                $icon   = match($diag['status']) { 'success' => '✔', 'failed' => '✘', 'skipped' => '⊘', default => '?' };
                $timing = $diag['elapsed_ms'] !== null ? " [{$diag['elapsed_ms']}ms]" : '';
                $fmt    = $diag['response_format'] !== 'unknown' ? " | fmt:{$diag['response_format']}" : '';
                $len    = $diag['content_length'] !== null ? " | {$diag['content_length']} chars" : '';
                $http   = $diag['http_status'] !== null ? " | HTTP {$diag['http_status']}" : '';

                $statusLine = "  {$icon} [{$diag['provider']}] {$diag['model']}{$timing}{$http}{$fmt}{$len}";
                if (!empty($diag['error'])) {
                    $statusLine .= " → " . $diag['error'];
                }
                $addLog($diag['status'] === 'success' ? 'success' : ($diag['status'] === 'skipped' ? 'warn' : 'error'), $statusLine);

                if (!empty($diag['raw_snippet'])) {
                    $addLog('warn', "  RAW: " . substr($diag['raw_snippet'], 0, 200));
                }
            }

            if (!$draft || mb_strlen(trim($draft)) < 300) {
                $draftLen = $draft ? mb_strlen(trim($draft)) : 0;
                $reason   = $draft === null
                    ? 'AI return null — semua provider gagal (lihat diagnostik di atas)'
                    : "Draft terlalu pendek: {$draftLen} karakter (minimum 300)";

                $job->update(['status' => 'failed', 'error_log' => ['reason' => "Phase 1: {$reason}"]]);
                $content->update(['status' => 'failed_cqi']);
                $addLog('error', "Phase 1 GAGAL: {$reason}");
                return ['success' => false, 'error' => "Phase 1 GAGAL: {$reason}", 'logs' => $logs, 'keyword' => $keyword];
            }


            $job->update(['status' => 'phase_2', 'phase_1_draft' => $draft]);
            $addLog('success', "Phase 1 SELESAI | Draft: " . mb_strlen($draft) . " karakter");

            // ── PHASE 2: CQI Critique ─────────────────────────────────────────
            $addLog('info', "Phase 2: CQI Quality Check untuk [{$keyword}]...");
            $aiService2 = new \App\Services\AIService($tenant, 'default');
            $sysP2 = \App\Models\SystemSetting::get('ai_prompt_phase2_sys',
                "You are a strict Senior SEO Content Auditor. Evaluate the article draft and respond ONLY with valid JSON:\n{\"cqi_score\": <0-100>, \"strengths\": [], \"gaps\": [], \"improvements\": []}");
            $critique = $aiService2->generateJson($sysP2, "Keyword: {$keyword}\n\nDraft:\n{$draft}");

            if (!$critique || !isset($critique['cqi_score'])) {
                // If critique fails, use a reasonable default and continue
                $critique = ['cqi_score' => 75, 'gaps' => [], 'improvements' => ['Improve E-E-A-T signals and depth.']];
                $addLog('warn', "Phase 2: Critique tidak dapat di-parse, menggunakan skor default 75.");
            }

            $cqiScore = (int) $critique['cqi_score'];
            $job->update(['status' => 'phase_3', 'phase_2_critique' => $critique]);
            $addLog('info', "Phase 2 SELESAI | CQI Score: {$cqiScore}/100");

            $cqiThreshold = (int) \App\Models\SystemSetting::get('ai_cqi_threshold', 70);
            if ($cqiScore < $cqiThreshold) {
                $addLog('warn', "CQI {$cqiScore} di bawah threshold {$cqiThreshold}. Artikel tetap diproses dengan catatan improvement.");
            }

            // ── PHASE 3: Expansion ────────────────────────────────────────────
            $addLog('info', "Phase 3: Expanding & enriching content...");
            $aiService3 = new \App\Services\AIService($tenant, 'default');
            $improvements = implode("\n- ", $critique['improvements'] ?? ['Improve depth and E-E-A-T']);
            $gaps         = implode("\n- ", $critique['gaps'] ?? []);
            $sysP3 = \App\Models\SystemSetting::get('ai_prompt_phase3_sys',
                "You are a Master SEO Content Expander writing in {lang}. Rewrite and expand the article to address ALL gaps and improvements. Minimum 1,800 words. Return ONLY the improved Markdown.");
            $sysP3 = strtr($sysP3, ['{lang}' => $lang, '{keyword}' => $keyword]);
            $userP3 = "Keyword: **{$keyword}**\n\nOriginal Draft:\n{$draft}\n\nGaps:\n- {$gaps}\n\nImprovements:\n- {$improvements}\n\nRewrite and expand now:";

            $expanded = $aiService3->generate($sysP3, $userP3);

            if (!$expanded || mb_strlen(trim($expanded)) < 300) {
                $expanded = $draft; // Fall back to Phase 1 draft if expansion fails
                $addLog('warn', "Phase 3: Expansion gagal, menggunakan draft Phase 1.");
            } else {
                $addLog('success', "Phase 3 SELESAI | Expanded: " . mb_strlen($expanded) . " karakter");
            }

            $job->update(['status' => 'phase_4', 'phase_3_expanded' => $expanded]);

            // ── PHASE 4: Master Edit + Links + Publish ────────────────────────
            $addLog('info', "Phase 4: Master edit, internal links & SEO meta...");
            $aiService4 = new \App\Services\AIService($tenant, 'default');

            $deterministicLinks = \App\Models\DeterministicLink::where('source_content_id', $content->id)
                ->with('targetContent')->get();
            $linkInstructions = '';
            if ($deterministicLinks->isNotEmpty()) {
                $linkInstructions = "\n\nMANDATORY INTERNAL LINKS (embed all using Markdown):\n";
                foreach ($deterministicLinks as $link) {
                    $url = url('/blog/' . ($link->targetContent?->slug ?? '#'));
                    $linkInstructions .= "- [{$link->anchor_text}]({$url})\n";
                }
            }
            $imageInstruction = '';
            if ($content->featured_image_url) {
                $imageInstruction = "\n\nFEATURED IMAGE at top:\n![{$content->featured_image_alt}]({$content->featured_image_url})";
            }

            $sysP4 = \App\Models\SystemSetting::get('ai_prompt_phase4_sys',
                "You are a Chief Content Editor writing in {lang}. Final editorial pass: improve readability, inject all internal links naturally, add featured image if provided, ensure strong CTA in conclusion. Return ONLY the final Markdown.");
            $sysP4 = strtr($sysP4, ['{lang}' => $lang, '{keyword}' => $keyword]);
            $userP4 = "Keyword: **{$keyword}**\n\nArticle:\n{$expanded}{$linkInstructions}{$imageInstruction}";

            $finalBody = $aiService4->generate($sysP4, $userP4);

            if (!$finalBody || mb_strlen(trim($finalBody)) < 300) {
                $finalBody = $expanded; // Fall back to Phase 3 if final edit fails
                $addLog('warn', "Phase 4: Final edit gagal, menggunakan konten Phase 3.");
            } else {
                $addLog('success', "Phase 4 SELESAI | Final: " . mb_strlen($finalBody) . " karakter");
            }

            // ── Save to DB ────────────────────────────────────────────────────
            $blogPrefix  = \App\Models\SystemSetting::get('permalink_blog', 'blog');
            $contentHash = hash('sha256', $finalBody);

            $job->update([
                'status'        => 'completed',
                'phase_4_final' => $finalBody,
                'completed_at'  => now(),
            ]);

            if ($deterministicLinks->isNotEmpty()) {
                \App\Models\DeterministicLink::where('source_content_id', $content->id)
                    ->update(['is_injected' => true]);
            }

            $content->body_raw = $finalBody;
            $content->update([
                'cqi_score'    => $cqiScore,
                'content_hash' => $contentHash,
                'status'       => $targetStatus,
                'published_at' => $content->published_at ?? now(),
            ]);
            $content->save();

            // ── Phase 5: SEO Meta (non-blocking) ─────────────────────────────
            try {
                $metaTitlePrompt = str_replace('{keyword}', $keyword, \App\Models\SystemSetting::get('ai_prompt_meta_title',
                    'Write a highly click-worthy SEO title for "{keyword}". Max 60 chars. Return ONLY the title.'));
                $metaDescPrompt  = str_replace('{keyword}', $keyword, \App\Models\SystemSetting::get('ai_prompt_meta_description',
                    'Write an engaging SEO meta description for "{keyword}". 150-160 chars with CTA. Return ONLY the description.'));

                $metaTitle = trim($aiService4->generate('You are an expert SEO specialist.', $metaTitlePrompt), " \t\n\r\"'");
                $metaDesc  = trim($aiService4->generate('You are an expert SEO specialist.', $metaDescPrompt), " \t\n\r\"'");

                $content->updateSeoMeta([
                    'title'          => $metaTitle ?: $content->title,
                    'description'    => $metaDesc,
                    'canonical'      => url('/' . $blogPrefix . '/' . $content->slug),
                    'robots'         => 'index, follow',
                    'og_title'       => $metaTitle ?: $content->title,
                    'og_description' => $metaDesc,
                    'og_image'       => $content->featured_image_url ?: \App\Models\SystemSetting::get('seo_og_image'),
                ]);
                $addLog('success', "SEO Meta dibuat: \"{$metaTitle}\"");
            } catch (\Exception $e) {
                $addLog('warn', "SEO Meta gagal (non-fatal): " . $e->getMessage());
            }

            $addLog('success', "✅ [{$keyword}] SELESAI → status: {$targetStatus} | CQI: {$cqiScore}/100 | {$contentHash}");

            return [
                'success' => true,
                'keyword' => $keyword,
                'title'    => $content->title,
                'cqi'      => $cqiScore,
                'status'   => $targetStatus,
                'logs'     => $logs,
            ];

        } catch (\Throwable $e) {
            if (isset($job) && $job) {
                $job->update(['status' => 'failed', 'error_log' => ['reason' => $e->getMessage()]]);
            }
            if (isset($content) && $content) {
                $content->update(['status' => 'failed_cqi']);
            }
            
            $errorMsg = "FATAL ERROR: " . $e->getMessage() . " on line " . $e->getLine();
            if (isset($addLog)) {
                $addLog('error', $errorMsg);
                return ['success' => false, 'keyword' => $keyword ?? 'Unknown', 'error' => $errorMsg, 'logs' => $logs];
            }
            
            return ['success' => false, 'error' => $errorMsg, 'logs' => []];
        }
    }




    /**
     * Check connectivity to the configured AI provider.
     * Called by the frontend before starting the AI Worker to verify the API
     * key/endpoint is reachable. Returns provider info and ok/error status.
     */
    public function checkConnection()
    {
        $tenant    = \App\Models\Tenant::first();
        $aiService = new \App\Services\AIService($tenant, 'default');
        $result    = $aiService->testConnection();

        return response()->json([
            'ok'          => $result['ok'],
            'provider'    => $result['provider'],
            'model'       => $result['model'],
            'error'       => $result['error'],
            'diagnostics' => $result['diagnostics'] ?? [],
        ]);
    }

    /**
     * Trigger queue worker manually via AJAX.
     * Returns rich per-job status details so the terminal can display
     * phase-by-phase progress information.
     */
    public function workQueue(Request $request)
    {
        if (function_exists('set_time_limit')) {
            @set_time_limit(120);
        }

        $activeStatuses = ['pending', 'processing', 'phase_1', 'phase_2', 'phase_3', 'phase_4'];

        try {
            $hasJobsInQueue = \Illuminate\Support\Facades\DB::table('jobs')->exists();
            $hasMore        = false;
            $logs           = [];

            // --- Take snapshot of all active jobs BEFORE running the worker ---
            $jobsBefore = \App\Models\AiGenerationJob::withoutGlobalScopes()
                ->whereIn('status', $activeStatuses)
                ->with(['content' => fn($q) => $q->withoutGlobalScopes()])
                ->get()
                ->keyBy('id');

            if (!$hasJobsInQueue) {
                // Queue table empty — check for orphaned DB jobs
                $stuckJobs = \App\Models\AiGenerationJob::withoutGlobalScopes()
                    ->whereIn('status', $activeStatuses)
                    ->with(['content' => fn($q) => $q->withoutGlobalScopes()])
                    ->get();

                if ($stuckJobs->isNotEmpty()) {
                    foreach ($stuckJobs as $stuck) {
                        $stuck->update([
                            'status'    => 'failed',
                            'error_log' => ['error' => 'Job execution timed out or was killed by server.'],
                        ]);
                        $stuck->content?->update(['status' => 'failed_cqi']);

                        $logs[] = [
                            'level'   => 'error',
                            'message' => "JOB #{$stuck->id} [{$stuck->content?->target_keyword}] → Cleaned up as STUCK (queue empty but DB shows active)",
                        ];
                    }
                } else {
                    $logs[] = ['level' => 'info', 'message' => 'Queue empty. All jobs finished or no jobs queued.'];
                }

                $hasMore = false;
            } else {
                // Run exactly one queued job
                \Illuminate\Support\Facades\Artisan::call('queue:work', [
                    '--once'           => true,
                    '--force'          => true,
                    '--stop-when-empty'=> true,
                ]);

                // --- Take snapshot AFTER running ---
                $jobsAfter = \App\Models\AiGenerationJob::withoutGlobalScopes()
                    ->with(['content' => fn($q) => $q->withoutGlobalScopes()])
                    ->whereIn('id', $jobsBefore->keys()->toArray())
                    ->get()
                    ->keyBy('id');

                // Also check for any newly dispatched jobs from CQI retries
                $allActiveNow = \App\Models\AiGenerationJob::withoutGlobalScopes()
                    ->whereIn('status', $activeStatuses)
                    ->with(['content' => fn($q) => $q->withoutGlobalScopes()])
                    ->get();

                // Build per-job log lines
                foreach ($jobsBefore as $id => $before) {
                    $after    = $jobsAfter->get($id);
                    $keyword  = $before->content?->target_keyword ?? 'Unknown';
                    $title    = $before->content?->title ?? "Content #{$before->content_id}";
                    $elapsed  = $before->started_at ? now()->diffInSeconds($before->started_at) . 's' : '-';

                    if (!$after) {
                        $logs[] = ['level' => 'info', 'message' => "JOB #{$id} [{$keyword}] → No longer in active list (may have completed or failed)"];
                        continue;
                    }

                    $fromStatus = strtoupper($before->status);
                    $toStatus   = strtoupper($after->status);

                    $phaseLabel = match($after->status) {
                        'phase_1'  => '📝 Phase 1 — Generating Initial Draft',
                        'phase_2'  => '🔍 Phase 2 — Quality Critique & CQI Scoring',
                        'phase_3'  => '✍️  Phase 3 — Expanding & Enriching Content',
                        'phase_4'  => '🎨 Phase 4 — Master Edit & Link Injection',
                        'completed'=> '✅ COMPLETED — Content saved to DB',
                        'failed'   => '❌ FAILED — ' . (($after->error_log['reason'] ?? $after->error_log['error'] ?? 'Unknown error')),
                        'failed_cqi' => '⚠️  CQI FAILED — Retrying Phase 1',
                        default    => strtoupper($after->status),
                    };

                    $cqiInfo    = '';
                    $retryInfo  = '';
                    if ($after->phase_2_critique && isset($after->phase_2_critique['cqi_score'])) {
                        $cqiInfo = " | CQI: {$after->phase_2_critique['cqi_score']}/100";
                    }
                    if ($after->retry_count > 0) {
                        $retryInfo = " | Retry: {$after->retry_count}/2";
                    }

                    $level = match(true) {
                        $after->status === 'failed'     => 'error',
                        $after->status === 'failed_cqi' => 'warn',
                        $after->status === 'completed'  => 'success',
                        default                          => 'info',
                    };

                    // Status transition log
                    if ($fromStatus !== $toStatus) {
                        $logs[] = [
                            'level'   => $level,
                            'message' => "JOB #{$id} [{$keyword}]{$cqiInfo}{$retryInfo} → {$fromStatus} ➜ {$phaseLabel}",
                        ];
                    } else {
                        // Status unchanged (still same phase — running)
                        $logs[] = [
                            'level'   => 'running',
                            'message' => "JOB #{$id} [{$keyword}] — {$phaseLabel}{$cqiInfo}{$retryInfo} (elapsed: {$elapsed})",
                        ];
                    }

                    // If completed, show what content was saved
                    if ($after->status === 'completed') {
                        $bodyLen  = $after->phase_4_final ? mb_strlen($after->phase_4_final) : 0;
                        $cqiFinal = $after->phase_2_critique['cqi_score'] ?? 'N/A';
                        $logs[] = [
                            'level'   => 'success',
                            'message' => "   └─ \"{$title}\" saved | CQI: {$cqiFinal}/100 | Body: {$bodyLen} chars | Status: {$after->content?->status}",
                        ];
                    }

                    // If failed, show the reason
                    if ($after->status === 'failed') {
                        $reason = $after->error_log['reason'] ?? $after->error_log['error'] ?? 'No reason recorded';
                        $logs[] = [
                            'level'   => 'error',
                            'message' => "   └─ REASON: {$reason}",
                        ];
                    }
                }

                // Show count of remaining jobs
                $remainingCount = $allActiveNow->count();
                $hasMore        = $remainingCount > 0;

                if ($hasMore) {
                    $logs[] = [
                        'level'   => 'info',
                        'message' => "─── {$remainingCount} job(s) still in queue. Processing next... ───",
                    ];
                } else {
                    $logs[] = [
                        'level'   => 'success',
                        'message' => '═══ All AI generation jobs completed! ═══',
                    ];
                }
            }

            return response()->json([
                'success' => true,
                'logs'    => $logs,
                'has_more'=> $hasMore,
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'success'  => false,
                'logs'     => [['level' => 'error', 'message' => 'FATAL: ' . $e->getMessage()]],
                'has_more' => \App\Models\AiGenerationJob::withoutGlobalScopes()
                    ->whereIn('status', $activeStatuses)->exists(),
            ]);
        }
    }




    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Content $content)
    {

        $content->delete();

        return redirect()->route('admin.content.index')
            ->with('success', 'Post successfully deleted.');
    }
}
