<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Content;
use App\Models\SiloBlueprint;
use App\Models\AiGenerationJob;
use App\Jobs\Ai\ProcessAiGenerationJob;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ContentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $contents = Content::withoutGlobalScopes()
            ->where('status', 'published')
            ->with(['siloBlueprint', 'latestUrlInspection'])
            ->latest()
            ->paginate(20);

        return view('admin.content.index', compact('contents'));
    }

    /**
     * Display a listing of the Pra Post (Blueprint) contents ready for AI generation.
     */
    public function prapost()
    {
        // Show blueprint status so user can generate blueprints
        $contents = Content::withoutGlobalScopes()
            ->whereIn('status', ['blueprint', 'failed_cqi'])
            ->with(['siloBlueprint'])
            ->latest()
            ->paginate(20);

        return view('admin.content.prapost', compact('contents'));
    }

    /**
     * Display a listing of Draft contents generated by AI.
     */
    public function drafts()
    {
        $contents = Content::withoutGlobalScopes()
            ->whereIn('status', ['draft', 'needs_reoptimize'])
            ->with(['siloBlueprint'])
            ->latest()
            ->paginate(20);

        return view('admin.content.drafts', compact('contents'));
    }

    /**
     * Show the form for creating a new resource (Write with AI).
     */
    public function create()
    {
        $activeJobs = AiGenerationJob::withoutGlobalScopes()
            ->whereIn('status', ['pending', 'processing', 'phase_1', 'phase_2', 'phase_3', 'phase_4'])
            ->with(['content' => function($q) {
                $q->withoutGlobalScopes();
            }])
            ->latest()
            ->get();
            
        $processingContents = Content::withoutGlobalScopes()
            ->where('status', 'ai_processing')
            ->latest()
            ->get();

        return view('admin.content.create', compact('activeJobs', 'processingContents'));
    }

    /**
     * Store a newly created resource in storage (Dispatch AI Generator).
     */
    public function store(Request $request)
    {
        $request->validate([
            'target_keyword' => 'required|string|max:255',
            'hierarchy_level' => 'required|string|in:pillar,cluster,sub_cluster',
            'silo_blueprint_id' => 'required|exists:silo_blueprints,id',
        ]);

        $slug = Str::slug($request->target_keyword);

        // Check for duplicate slugs
        $exists = Content::withoutGlobalScopes()->where(function($q) use ($slug) {
            $q->where('slug', $slug)->orWhere('slug', 'LIKE', '%"id":"'.$slug.'"%');
        })->exists();
        if ($exists) {
            $slug .= '-' . rand(100, 999);
        }

        $generateAi = $request->has('generate_ai');

        // Create Content model
        $content = Content::create([
            'tenant_id'        => \App\Models\Tenant::first()?->id ?? 1,
            'silo_blueprint_id' => $request->silo_blueprint_id,
            'target_keyword'   => $request->target_keyword,
            'slug'             => ['id' => $slug],
            'meta_title'       => ['id' => ucwords($request->target_keyword) . ' - SEOFAST'],
            'meta_description' => ['id' => 'Panduan taktis terperinci mengenai ' . $request->target_keyword . ' untuk optimasi mesin pencari.'],
            'hierarchy_level' => $request->hierarchy_level,
            'status' => $generateAi ? 'ai_processing' : 'blueprint',
        ]);

        // Calculate crawl priority score: pillar gets highest, cluster medium, sub_cluster lowest
        $hierarchyWeight = match($request->hierarchy_level) {
            'pillar' => 1.0,
            'cluster' => 0.6,
            'sub_cluster' => 0.3,
            default => 0.3,
        };
        $searchVolume = (int) $request->get('search_volume', 0);
        $searchVolumeWeight = min($searchVolume / 1000, 1.0) * 0.4;
        $crawlPriority = round(($searchVolumeWeight) + ($hierarchyWeight * 0.6), 2);
        $content->update(['crawl_priority_score' => $crawlPriority]);

        if ($generateAi) {
            // Create AI Generation Job
            $job = AiGenerationJob::create([
                'tenant_id' => \App\Models\Tenant::first()?->id ?? 1,
                'content_id' => $content->id,
                'job_type' => 'initial_generation',
                'status' => 'pending',
                'llm_model_used' => \App\Models\SystemSetting::get('ai_model', 'gpt-4o'),
            ]);

            // Dispatch background processing job
            ProcessAiGenerationJob::dispatch($content->id, $job->id);

            return redirect()->route('admin.content.index')
                ->with('success', 'AI Generation Job has been queued. The article is being written in 4 distinct quality phases!');
        }

        return redirect()->route('admin.content.index')
            ->with('success', 'Keyword manually added as Blueprint!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Content $content)
    {
        $job = AiGenerationJob::withoutGlobalScopes()->where('content_id', $content->id)->latest()->first();

        return view('admin.content.show', compact('content', 'job'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Content $content)
    {
        $siloBlueprints = SiloBlueprint::withoutGlobalScopes()->get();

        return view('admin.content.edit', compact('content', 'siloBlueprints'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Content $content)
    {

        $request->validate([
            'target_keyword' => 'required|string|max:255',
            'hierarchy_level' => 'required|string|in:pillar,cluster,sub_cluster',
            'silo_blueprint_id' => 'required|exists:silo_blueprints,id',
            'body_raw' => 'nullable|string',
            'rendered_html_path' => 'nullable|string',
            'meta_title' => 'nullable|string|max:70',
            'meta_description' => 'nullable|string|max:160',
            'status' => 'required|string',
            'canonical' => 'nullable|url',
            'robots' => 'nullable|string',
            'og_title' => 'nullable|string',
            'og_description' => 'nullable|string',
            'og_image' => 'nullable|url',
            'schema_type' => 'nullable|string',
            'schema_custom_json' => 'nullable|string',
            'featured_image_upload' => 'nullable|image|mimes:jpeg,png,jpg,webp|max:2048',
            'featured_image_url' => 'nullable|string',
            'published_at' => 'nullable|date',
        ]);

        $updateData = $request->except(['canonical', 'robots', 'og_title', 'og_description', 'og_image', 'schema_type', 'schema_custom_json', 'featured_image_upload']);

        if ($request->hasFile('featured_image_upload')) {
            $path = $request->file('featured_image_upload')->store('content-images', 'public');
            $updateData['featured_image_url'] = '/storage/' . $path;
        }

        $content->update($updateData);

        // Build schema
        $schema = null;
        if ($request->schema_custom_json) {
            $parsed = json_decode($request->schema_custom_json, true);
            if (is_array($parsed)) {
                $schema = $parsed;
            }
        }
        if (!$schema && $request->schema_type && $request->schema_type !== 'None') {
            $schema = ['@type' => $request->schema_type];
        }

        // Update polymorphic SEO meta
        $content->updateSeoMeta([
            'title' => $request->meta_title,
            'description' => $request->meta_description,
            'canonical' => $request->canonical,
            'robots' => $request->robots ?? 'index, follow',
            'og_title' => $request->og_title,
            'og_description' => $request->og_description,
            'og_image' => $request->og_image,
            'schema' => $schema,
        ]);

        return redirect()->route('admin.content.show', $content->id)
            ->with('success', 'Content successfully updated manually.');
    }

    /**
     * Trigger AI Generation for a manual Blueprint.
     */
    public function generateAi(Content $content)
    {
        // Set status to ai_processing
        $content->update(['status' => 'ai_processing']);

        // Check if there's already a pending/processing job
        $existingJob = AiGenerationJob::withoutGlobalScopes()
            ->where('content_id', $content->id)
            ->whereIn('status', ['pending', 'processing'])
            ->first();

        if (!$existingJob) {
            $job = AiGenerationJob::create([
                'tenant_id'  => $content->tenant_id ?? (\App\Models\Tenant::first()?->id ?? 1),
                'content_id' => $content->id,
                'job_type'   => 'initial_generation',
                'status'     => 'pending',
                'retry_count'=> 0
            ]);

            ProcessAiGenerationJob::dispatch($content->id, $job->id);
            
            // Trigger background worker for shared hosting / Windows
            if (function_exists('popen') && function_exists('pclose')) {
                $php = PHP_BINARY;
                $artisan = base_path('artisan');
                if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
                    pclose(popen("start /B {$php} {$artisan} queue:work --stop-when-empty > NUL", "r"));
                } else {
                    exec("{$php} {$artisan} queue:work --stop-when-empty > /dev/null 2>&1 &");
                }
            }
        }

        return redirect()->route('admin.content.create')->with('success', 'AI Generation started for ' . $content->title);
    }

    public function bulkGenerateAi(Request $request)
    {
        $request->validate([
            'content_ids' => 'required|array',
            'content_ids.*' => 'exists:contents,id',
            'target_status' => 'nullable|string|in:draft,published'
        ]);

        $targetStatus = $request->input('target_status', 'draft');

        $count = 0;
        foreach ($request->content_ids as $id) {
            $content = Content::withoutGlobalScopes()->find($id);
            if ($content && in_array($content->status, ['blueprint', 'draft', 'failed_cqi', 'ai_processing'])) {
                $content->update(['status' => 'ai_processing']);
                
                $existingJob = AiGenerationJob::withoutGlobalScopes()
                    ->where('content_id', $content->id)
                    ->whereIn('status', ['pending', 'processing', 'phase_1', 'phase_2', 'phase_3', 'phase_4'])
                    ->first();

                if (!$existingJob) {
                    $job = AiGenerationJob::create([
                        'tenant_id'  => $content->tenant_id ?? (\App\Models\Tenant::first()?->id ?? 1),
                        'content_id' => $content->id,
                        'job_type'   => 'initial_generation',
                        'status'     => 'pending',
                        'retry_count'=> 0
                    ]);

                    ProcessAiGenerationJob::dispatch($content->id, $job->id, $targetStatus);
                    $count++;
                }
            }
        }
        
        // Trigger background worker for shared hosting / Windows
        if ($count > 0 && function_exists('popen') && function_exists('pclose')) {
            $php = PHP_BINARY;
            $artisan = base_path('artisan');
            if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
                pclose(popen("start /B {$php} {$artisan} queue:work --stop-when-empty > NUL", "r"));
            } else {
                exec("{$php} {$artisan} queue:work --stop-when-empty > /dev/null 2>&1 &");
            }
        }

        return redirect()->route('admin.content.create')->with('success', $count . ' contents queued for AI generation.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Content $content)
    {

        $content->delete();

        return redirect()->route('admin.content.index')
            ->with('success', 'Post successfully deleted.');
    }
}
